version: "3.1"

services:

  php:
    container_name: ${PROJECT_NAME}_php_${VERSION_ID}
    build:
      context: ./docker/php
      args:
        - XDEBUG=${XDEBUG}
    ports:
      - 9000:9000
    networks:
      - backend
    volumes:
      - ./app:/srv/app:cached
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      APP_URL: ${APP_URL}
      TIME_ZONE: ${TIME_ZONE}
      DB_HOST: db:${DB_PORT_EXPOSED}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
 
  web:
    container_name: ${PROJECT_NAME}_web_${VERSION_ID}
    build:
      context: ./docker/nginx
    ports:
      - ${HTTP_PORT_EXPOSED}:80
      # - ${HTTPS_PORT_EXPOSED}:443
    networks:
      - backend
      - frontend
    volumes:
      - ./app:/srv/app:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/app:/var/log/nginx
      # - ./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template.conf:ro
      # - ./docker/nginx/certs:/etc/nginx/certs:ro
    # environment:
    #   PROJECT_NAME: ${PROJECT_NAME}
    depends_on:
      - php

  db:
    container_name: ${PROJECT_NAME}_db_${VERSION_ID}
    build:
      context: ./docker/mariadb
    ports:
      - ${DB_PORT_EXPOSED}:3306
    volumes:
      - ./db:/var/lib/mysql
      # - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      - ./logs/db:/var/log/mysql
    networks:
      - backend
    environment:
      TZ: ${TIME_ZONE}
      DB_ROOT_PASSWORD: ${DB_ROOTPASS}
      DB_ROOT_HOST: "%"
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}

networks:
  frontend:
  backend: