version: "3.1"

services:

  php:
    container_name: ${PROJECT_NAME}_php_${VERSION_ID}
    build:
      context: ./docker/php
      args:
        - XDEBUG=${XDEBUG}
        - COMPOSER=${COMPOSER}
    ports:
      - 9000:9000
    volumes:
      - ./src:/src:cached
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/usr/local/etc/php/logs
    environment:
      WEBAPP_URL: ${WEBAPP_URL}
      TIME_ZONE: ${TIME_ZONE}
      DB_HOST: db:${DB_PORT_EXPOSED}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
 
  web:
    container_name: ${PROJECT_NAME}_web_${VERSION_ID}
    build:
      context: ./docker/nginx
    ports:
      - ${HTTP_PORT_EXPOSED}:80
      - ${HTTPS_PORT_EXPOSED}:443
    volumes:
      - ./src:/src:ro
      - ./logs/web:/var/log/nginx
      - ./docker/nginx/default.template:/etc/nginx/conf.d/default.template
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    environment:
      HTTP_PORT_EXPOSED: ${HTTP_PORT_EXPOSED}
      HTTPS_PORT_EXPOSED: ${HTTPS_PORT_EXPOSED}
      SERVER_HOST_NAME: ${SERVER_HOST_NAME}
    depends_on:
      - php

  db:
    container_name: ${PROJECT_NAME}_db_${VERSION_ID}
    build:
      context: ./docker/mariadb
    ports:
      - ${DB_PORT_EXPOSED}:3306
    volumes:
      # - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
      - ./logs/db:/var/log/mysql
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
